FtcRobotController/build.gradle, TeamCode/build.gradle, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ColorSensorTestOp.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankInterface.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestLinearOp.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestTeleOp.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/readme.md
=> Transfer everything to new SDK,

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AttatchmentsInterface.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestLinearOp.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestTeleOp.java
=> 10/4 Start AttachmentsInterface,

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OrientationSensors.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestIMU.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestLinearOp.java
=> 10/8 Test Calibration and finalize self-balance code

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestIMU.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestLinearOp.java
=> 10/13 Calibrated drivestraight and spin_Right

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousTest.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VisionTrackTest.java
=> 10/20 Start Vision Track, layout autonomous op mode

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestSpinPivot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VisionTrackTest.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaLetterTest.java
=> Code and naming cleanups

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java
=> 10/22 Finish vision track function to return column pos

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoAudi.java
=> 11/1 Import Sahiti's and Rhagav's autonomous program structures

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoAudi.java
=> Re-try to add initial values for BlueAutoAudi

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoAudi.java
=> Adjust red auto audi

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoRef.java
=> Edits in RedAutoRef and RedAuto Audi regarding the case statement

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoAudi.java
=> RedAutoAudi Adj Values

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoRef.java
=> Add logic to blue programs

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalRef.java
=> Universal programs, remove delays

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java
=> Adj color sens determinating values, comment out cm drivestr

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalRef.java
=> Programmed UniversalRef- 11/15

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalAudi.java
=> add floorColSens, add telemtry in uniAudi

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalRef.java
=> add delays to universal

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Start final versions of teleop + Robo class

TeamCode/src/main/java/JavaTestingSahithi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalRef.java
=> 11/19 Defaults programmed

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/liftTestTele.java
=> 11/19 Make concept wing code,

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> TeleOp + Robo finals

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Callibration_NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/liftTestTele.java
=> Adj lift direction; add cal class

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Callibration_NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/liftTestTele.java
=>  Add other functions of robo into robo class and add door code into lift test tele

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/LiftTestTele.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=>  Create functions for final robo class and final tele op 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=>  Create function for controlling lift w/o levels 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> Sahithi 12/8 finals finished

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=>  Attemp to fix tele and its functions 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Remove encoder func of drive for tele, adj servo values

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> Added pushing in glyph

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=> Started tweaks AutoAudi

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=>  Remove level shift function of lift, adj door values. Remove delays in audiUniFinal code

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Fixed problems with Audi/Teleop

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/LiftTestTele.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Hotel Day Changes: Add back in old moveLift, adjust some servo values.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ColorSensorTestOp.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Competition 12/16 Changes/Tweaks

TeamCode/src/main/java/JavaTestingSahithi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousTest.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Callibration_NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ColorSensorTestOp.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDev.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/LiftTestTele.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OrientationSensors.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestIMU.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestLinearOp.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VisionTrackTest.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaLetterTest.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/WingTester.java
=> Disable old stuff, increased power to attachments

TeamCode/build.gradle, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BlueAutoRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RedAutoRef.java
=> Sahithi tweaks AutoAudi

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ColorSensorTestOpProto.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDev.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OrientationSensors.java
=>  Determine color by value now

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=> Sensor sides

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> Changes to Ref

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Sahithi 12/29

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> Changes to Robot case

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> updated lift value

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDev.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Undo servo changes

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> FinalAudi changes to wing

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> adjust door code

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDev.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> remove servo ranges

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Callibration_NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDev.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Turn changes

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Callibration_NewRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDev.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> cal pivot, adj autonomou

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestStall.java
=> Stall drive function

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Stall function

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> FinalUniversalRef

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> FinalUniRef

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestStall.java
=>  Adjust Audi, make drive stall compatible with programming base

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TankBase.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestStall.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestStallCompBot.java
=> Add test stall to final robot, add comp robo test code 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Implement mag lim switches, adj door pos

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java
=>  swap controls for mouth, grsbber, and rotator

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> swap controls for mouth, grsbber, and rotator

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> add stop direction when lift/mouth hits a mag switch

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDev.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> add lift code from original implementation

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> More Ref Changes 1/21

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> remove redundant autonomous methods in NewRobotFinal

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> Case Statement added for left cipher to help angles that weren't a single value

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=>  Add check for opmode stopped in lift function

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalAudiAngles.java
=> Changed right red audi angle

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalAudiAngles.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=> moved code to universal audi from audi angle

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=> edited distance for closest spot of glyph box

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> tweaks to audi 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Hotel Day Changes: Adjust audi distances and angles b/c shallow and not too far. Remove imu initialization to fix crash issues. 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> comp day auto changes

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> turns to end of autonomus

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Potential fix to grabber and rotator spasm by storing values in variable

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestIMU.java
=> Fix tail position issues and implement self balancing in Teleop

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> changes from laptop

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java
=>  Add check to tail position when rewinding

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java
=> Add some comments in tele

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> blue ref right tweaks

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=>  Change angle 85 to 70 and compensate for angle to make breaking plane consistent

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=> Negate red angles to turn corrrectly

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=> add break statement in red left

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> red audi changes

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDemo.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=> Disable IMU and add tele-op Demo 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV2Controls.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java
=>  Added version 2 of the controls

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalRef.java
=> 2nd glyph to auto

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=> tweak to 2nd glyph audi

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FinalUniversalAudi.java
=> tweak to 2nd glyph audi #2

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV2Controls.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRobotFinal.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestTeleOp.java
=> Add self bal back

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBotTele.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestIMU.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestStall.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalAudi.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/UniversalRef.java
=> (PARADE BOT) Adjust deadzone to be smaller, added a toggle for speed mode;

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBot.java
=> Add in cal

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FollowWall.java
=> Sahithi 10/7 1

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ConceptAutonomousDepot.java
=> Created AutonomousDepot

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ConceptAutonomousDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FollowWallRevised.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBot.java
=> Follow Wall, fixed IMU crash, 

FtcRobotController/build.gradle, TeamCode/build.gradle, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBotTele.java
=> Fix gradle build issues

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FollowWallRevised.java
=> add in direction Tracker in followWall

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicBot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicBotTele.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ConceptAutonomousDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FollowWallRevised.java
=> add in Wallhug functionality in depot program, add in a basic Teleop program

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ConceptAutonomousDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/WallECalibrate.java
=>  work on wall hug program using simpler logic, add in regression value…  … …s for encoder pivot

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FollowWallRevised.java
=> edits wall follow

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicBotTele.java
=> add in encoder counts into Telemetry output in basicBotTele

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ConceptAutonomousDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBotUsingBasicBot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaFunctions.java
=>  add C. Alex's algorithm for following the wall

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ConceptAutonomousDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TensorFlow.java
=> tensor flow

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PictureFirstAuto.java
=> picture first auto

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ConceptAutonomousDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PictureFirstAuto.java
=> added follow wall to picture first

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ConceptTensorFlowObjectDetection.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TensorFlowDecisionTree.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaFunctions.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaTestOp.java
=>  Work on making tensorflow work, add functions in vuforiafunctions,  … start of a vuforia logic class.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobotCalibration.java
=> We made a program to move the robot left, right, forward, and backwards.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PictureFirstAuto.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/WallECalibrate.java
=> fixed pivot issue, added onto picture first

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> remove overloaded methods for driveStraight,

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FrontSensTest.java
=> edits to picture first

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobotCalibration.java
=> autofinal, and edits to calibration class

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> changed initial turn and added null zone back in 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> new distance reading method

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=>  add in if statements for encoder turns

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> cleaned up hug wall code

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> add prev steps in depot, start grabber methods 

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java
=> more changes to the wall approaching plan

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> finished picture first

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobotCalibration.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> deploy marker, new route depot, start teleop

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java
=> add in deploy marker in pic first

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> added in final drive to crater and distances forward

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> final depot and picture auto, new left hug wall

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> Finish CompTeleV1

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> add in climbing functionality and method.

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PracticeDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PracticePictureFirst.java
=> practice versions of picture and depot

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalPictureFirst.java
=> Adjusted angle in Picture First and distanes

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaFunctions.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaNavigator.java
=>  added some turns and drivestraights to make Robot flush w/ wall in Final and created new "Navigator" class

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> add in auto switches into compRobot

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java
=> switch auto program started

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=> finished switchdepot v1, created/finished switchpicture v1

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousRedFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobotCalibration.java
=> Changes to RedPicFinal

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousRedFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> Changes to auto and hug

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TensorFlowDecisionTree.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/ConceptAutonomousDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/FollowWallRevised.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/FrontSensTest.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/PictureFirstAuto.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/PracticePictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaFunctions.java
=>  Work on tensor flow detection, move stuff into test folder

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=> edited switch depot to match Jeremy's final depot code

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java
=> worked on switch depot hug wall

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java
=> finish Depot

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=> added case statements into switch picture to reverse displacement of sampling

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java
=> remove inital "twist"

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> Add in timer for lcibing

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java
=> minor changes to switch program

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=> time limit to lifter, sensor depth

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/ConceptTensorFlowObjectDetection.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/QuickBallPusherTeleOp.java
=> Disable ConceptTens program and create test program for servo

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/TestSamplingServo.java
=> rename test servo program

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/TestSamplingServo.java
=> add in functions for using the sampling device

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/TestSwitches.java
=> switch testing program

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/TestSwitches.java
=> narrowed switches to two switches, depot and crater

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> extender tele-op changes

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> tele-op changes

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java
=> quick reverse for collector extender

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> sahithi 1/21

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> reverse right wrist controls

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> undo sahiti's changes

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=> tweaks to deploying marker

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=>  remove tele-op code errors

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/PracticeDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/TensorFlowDecisionTree.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaFunctions.java
=>  possible fixes for multiple golds

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaFunctions.java
=>  new recognition program for sahiti and change vuforiaFunctions.getPos…  … …itionOfGoldInTwoObjects()

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=> tweaks to switch picture, scrapped sampling for picture

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=> tweaks to teleop extendeer

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=>  New recognization method for pic

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoDepotV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=> tweaks to switch depot, tensor to picture

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java
=>  simple change to wrist controls

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousBlueFinalPicture.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousFinalDepot.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonomousRedFinalPictureFirst.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompRobotCalibration.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SwitchAutoPictureV1.java
=> testing switches comp

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CompTeleDemoV1.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ParadeBotTele.java
=>  reverse ParadebotTele controls, create new CompTeleDemo for demo-ing

FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/SampleRevBlinkinLedDriver.java, TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestPrograms/LEDTesting.java
=> LED Testing class created, and enabled sample Blinkin Code
